version: '2'
  
volumes:
    mosquitto:
    config:

services:
  mosquitto-mqtt:
    build: ./mosquitto-mqtt
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - mosquitto:/mosquitto/data
  
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
       - 'config:/config'
       - 'config:/config/etc/localtime:ro'
    restart: always
    privileged: true
    network_mode: host
